export const SOLICITUD_PRODUCTOS = 'SOLICITUD_PRODUCTOS';
export const EXITO_PRODUCTOS = 'EXITO_PRODUCTOS';
export const FALLA_PRODUCTOS = 'FALLA_PRODUCTO';
export const REINICIO_PRODUCTOS = 'REINICIO_PRODUCTOS';

export const SOLICITUD_CREAR_PRODUCTO = 'SOLICITUD_PRODUCTO';
export const EXITO_CREAR_PRODUCTO = 'EXITO_PRODUCTO';
export const FALLA_CREAR_PRODUCTO = 'FALLA_PRODUCTO';
export const REINICIO_CREAR_PRODUCTO = 'REINICIO_PRODUCTO';
