export const SOLICITUD_USUARIO_LOGIN = 'SOLICITUD_USUARIO_LOGIN';
export const EXITO_USUARIO_LOGIN = 'EXITO_USUARIO_LOGIN';
export const FALLA_USUARIO_LOGIN = 'FALLA_USUARIO_LOGIN';
export const LOGOUT_USUARIO = 'LOGOUT_USUARIO';

export const SOLICITUD_USUARIO_REGISTRO = 'SOLICITUD_USUARIO_REGISTRO';
export const EXITO_USUARIO_REGISTRO = 'EXITO_USUARIO_REGISTRO';
export const FALLA_USUARIO_REGISTRO = 'FALLA_USUARIO_REGISTRO';
export const REINICIO_USUARIO_REGISTRO = 'REINICIO_USUARIO_REGISTRO';
