export const SOLICITUD_USUARIO_LOGIN = 'SOLICITUD_USUARIO_LOGIN';
export const EXITO_USUARIO_LOGIN = 'EXITO_USUARIO_LOGIN';
export const FALLA_USUARIO_LOGIN = 'FALLA_USUARIO_LOGIN';
export const LOGOUT_USUARIO = 'LOGOUT_USUARIO';

export const SOLICITUD_USUARIO_REGISTRO = 'SOLICITUD_USUARIO_REGISTRO';
export const EXITO_USUARIO_REGISTRO = 'EXITO_USUARIO_REGISTRO';
export const FALLA_USUARIO_REGISTRO = 'FALLA_USUARIO_REGISTRO';
export const REINICIO_USUARIO_REGISTRO = 'REINICIO_USUARIO_REGISTRO';

export const SOLICITUD_OBTENER_CLIENTE = 'SOLICITUD_OBTENER_CLIENTE';
export const EXITO_OBTENER_CLIENTE = 'EXITO_OBTENER_CLIENTE';
export const FALLA_OBTENER_CLIENTE = 'FALLA_OBTENER_CLIENTE';
export const REINICIO_OBTENER_CLIENTE = 'REINICIO_OBTENER_CLIENTE';

export const SOLICITUD_OBTENER_VENDEDOR = 'SOLICITUD_OBTENER_VENDEDOR';
export const EXITO_OBTENER_VENDEDOR = 'EXITO_OBTENER_VENDEDOR';
export const FALLA_OBTENER_VENDEDOR = 'FALLA_OBTENER_VENDEDOR';
export const REINICIO_OBTENER_VENDEDOR = 'REINICIO_OBTENER_VENDEDOR';