export const SOLICITUD_CREAR_ORDEN = 'SOLICITUD_CREAR_ORDEN';
export const EXITO_CREAR_ORDEN = 'EXITO_CREAR_ORDEN';
export const FALLA_CREAR_ORDEN = 'FALLA_CREAR_ORDEN';
export const REINICIO_CREAR_ORDEN = 'REINICIO_CREAR_ORDEN';

export const SOLICITUD_EDITAR_ORDEN = 'SOLICITUD_EDITAR_ORDEN';
export const EXITO_EDITAR_ORDEN = 'EXITO_EDITAR_ORDEN';
export const FALLA_EDITAR_ORDEN = 'FALLA_EDITAR_ORDEN';
export const REINICIO_EDITAR_ORDEN = 'REINICIO_EDITAR_ORDEN';

export const SOLICITUD_MIS_ORDENES_CLIENTE = 'SOLICITUD_MIS_ORDENES_CLIENTE';
export const EXITO_MIS_ORDENES_CLIENTE = 'EXITO_MIS_ORDENES_CLIENTE';
export const FALLA_MIS_ORDENES_CLIENTE = 'FALLA_MIS_ORDENES_CLIENTE';
export const REINICIO_MIS_ORDENES_CLIENTE = 'REINICIO_MIS_ORDENES_CLIENTE';

export const SOLICITUD_MIS_ORDENES_VENDEDOR = 'SOLICITUD_MIS_ORDENES_VENDEDOR';
export const EXITO_MIS_ORDENES_VENDEDOR = 'EXITO_MIS_ORDENES_VENDEDOR';
export const FALLA_MIS_ORDENES_VENDEDOR = 'FALLA_MIS_ORDENES_VENDEDOR';
export const REINICIO_MIS_ORDENES_VENDEDOR = 'REINICIO_MIS_ORDENES_VENDEDOR';